{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "\n",
    "1) customer exception will inherit the properties of base exception class\n",
    "2) it will help python to undertstand customer exceptions are extend of error handling mechanism \n",
    "3) because of inheritance , custom exceptions can be utilized with try & except blocks seamlessly\n",
    "4) we can leverage \"raise\" keyword to throw error messages \n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Q2. Write a python program to print Python Exception Hierarchy.\n",
    "\n",
    "All exceptions are derived from base class called \"Base Exception\" and all standard exceptions inherit from this class "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "exception hierarchy\n",
      "<class 'Exception'>\n",
      "<class 'TypeError'>\n",
      "<class 'decimal.FloatOperation'>\n",
      "<class 'email.errors.MultipartConversionError'>\n",
      "<class 'StopAsyncIteration'>\n",
      "<class 'StopIteration'>\n",
      "<class 'ImportError'>\n",
      "<class 'ModuleNotFoundError'>\n",
      "<class 'importlib.metadata.PackageNotFoundError'>\n",
      "<class 'zipimport.ZipImportError'>\n",
      "<class 'OSError'>\n",
      "<class 'ConnectionError'>\n",
      "<class 'BrokenPipeError'>\n",
      "<class 'ConnectionAbortedError'>\n",
      "<class 'ConnectionRefusedError'>\n",
      "<class 'ConnectionResetError'>\n",
      "<class 'http.client.RemoteDisconnected'>\n",
      "<class 'BlockingIOError'>\n",
      "<class 'ChildProcessError'>\n",
      "<class 'FileExistsError'>\n",
      "<class 'FileNotFoundError'>\n",
      "<class 'IsADirectoryError'>\n",
      "<class 'NotADirectoryError'>\n",
      "<class 'InterruptedError'>\n",
      "<class 'zmq.error.InterruptedSystemCall'>\n",
      "<class 'PermissionError'>\n",
      "<class 'ProcessLookupError'>\n",
      "<class 'TimeoutError'>\n",
      "<class 'io.UnsupportedOperation'>\n",
      "<class 'socket.herror'>\n",
      "<class 'socket.gaierror'>\n",
      "<class 'ssl.SSLError'>\n",
      "<class 'ssl.SSLCertVerificationError'>\n",
      "<class 'ssl.SSLZeroReturnError'>\n",
      "<class 'ssl.SSLWantWriteError'>\n",
      "<class 'ssl.SSLWantReadError'>\n",
      "<class 'ssl.SSLSyscallError'>\n",
      "<class 'ssl.SSLEOFError'>\n",
      "<class 'shutil.Error'>\n",
      "<class 'shutil.SameFileError'>\n",
      "<class 'shutil.SpecialFileError'>\n",
      "<class 'shutil.ExecError'>\n",
      "<class 'shutil.ReadError'>\n",
      "<class 'urllib.error.URLError'>\n",
      "<class 'urllib.error.HTTPError'>\n",
      "<class 'urllib.error.ContentTooShortError'>\n",
      "<class 'gzip.BadGzipFile'>\n",
      "<class 'EOFError'>\n",
      "<class 'asyncio.exceptions.IncompleteReadError'>\n",
      "<class 'RuntimeError'>\n",
      "<class 'RecursionError'>\n",
      "<class 'NotImplementedError'>\n",
      "<class 'zmq.error.ZMQVersionError'>\n",
      "<class 'IPython.core.error.StdinNotImplementedError'>\n",
      "<class '_frozen_importlib._DeadlockError'>\n",
      "<class 'threading.BrokenBarrierError'>\n",
      "<class 'concurrent.futures._base.BrokenExecutor'>\n",
      "<class 'concurrent.futures.thread.BrokenThreadPool'>\n",
      "<class 'asyncio.exceptions.SendfileNotAvailableError'>\n",
      "<class '_pydevd_bundle.pydevd_vars.VariableError'>\n",
      "<class 'NameError'>\n",
      "<class 'UnboundLocalError'>\n",
      "<class 'AttributeError'>\n",
      "<class 'dataclasses.FrozenInstanceError'>\n",
      "<class 'SyntaxError'>\n",
      "<class 'IndentationError'>\n",
      "<class 'TabError'>\n",
      "<class 'LookupError'>\n",
      "<class 'IndexError'>\n",
      "<class 'KeyError'>\n",
      "<class 'jupyter_client.kernelspec.NoSuchKernel'>\n",
      "<class 'IPython.terminal.pt_inputhooks.UnknownBackend'>\n",
      "<class 'encodings.CodecRegistryError'>\n",
      "<class 'ValueError'>\n",
      "<class 'UnicodeError'>\n",
      "<class 'UnicodeEncodeError'>\n",
      "<class 'UnicodeDecodeError'>\n",
      "<class 'UnicodeTranslateError'>\n",
      "<class 'io.UnsupportedOperation'>\n",
      "<class 'json.decoder.JSONDecodeError'>\n",
      "<class 'ssl.SSLCertVerificationError'>\n",
      "<class 'binascii.Error'>\n",
      "<class '_hashlib.UnsupportedDigestmodError'>\n",
      "<class 'calendar.IllegalMonthError'>\n",
      "<class 'calendar.IllegalWeekdayError'>\n",
      "<class 'dateutil.parser._parser.ParserError'>\n",
      "<class 'email.errors.MessageDefect'>\n",
      "<class 'email.errors.NoBoundaryInMultipartDefect'>\n",
      "<class 'email.errors.StartBoundaryNotFoundDefect'>\n",
      "<class 'email.errors.CloseBoundaryNotFoundDefect'>\n",
      "<class 'email.errors.FirstHeaderLineIsContinuationDefect'>\n",
      "<class 'email.errors.MisplacedEnvelopeHeaderDefect'>\n",
      "<class 'email.errors.MissingHeaderBodySeparatorDefect'>\n",
      "<class 'email.errors.MultipartInvariantViolationDefect'>\n",
      "<class 'email.errors.InvalidMultipartContentTransferEncodingDefect'>\n",
      "<class 'email.errors.UndecodableBytesDefect'>\n",
      "<class 'email.errors.InvalidBase64PaddingDefect'>\n",
      "<class 'email.errors.InvalidBase64CharactersDefect'>\n",
      "<class 'email.errors.InvalidBase64LengthDefect'>\n",
      "<class 'email.errors.HeaderDefect'>\n",
      "<class 'email.errors.InvalidHeaderDefect'>\n",
      "<class 'email.errors.HeaderMissingRequiredValue'>\n",
      "<class 'email.errors.NonPrintableDefect'>\n",
      "<class 'email.errors.ObsoleteHeaderDefect'>\n",
      "<class 'email.errors.NonASCIILocalPartDefect'>\n",
      "<class 'email.errors.InvalidDateDefect'>\n",
      "<class 'pygments.util.ClassNotFound'>\n",
      "<class 'IPython.lib.clipboard.ClipboardEmpty'>\n",
      "<class 'IPython.core.magics.code.MacroToEdit'>\n",
      "<class 'packaging.version.InvalidVersion'>\n",
      "<class 'AssertionError'>\n",
      "<class 'ArithmeticError'>\n",
      "<class 'FloatingPointError'>\n",
      "<class 'OverflowError'>\n",
      "<class 'ZeroDivisionError'>\n",
      "<class 'decimal.DivisionByZero'>\n",
      "<class 'decimal.DivisionUndefined'>\n",
      "<class 'decimal.DecimalException'>\n",
      "<class 'decimal.Clamped'>\n",
      "<class 'decimal.Rounded'>\n",
      "<class 'decimal.Underflow'>\n",
      "<class 'decimal.Overflow'>\n",
      "<class 'decimal.Inexact'>\n",
      "<class 'decimal.Underflow'>\n",
      "<class 'decimal.Overflow'>\n",
      "<class 'decimal.Subnormal'>\n",
      "<class 'decimal.Underflow'>\n",
      "<class 'decimal.DivisionByZero'>\n",
      "<class 'decimal.FloatOperation'>\n",
      "<class 'decimal.InvalidOperation'>\n",
      "<class 'decimal.ConversionSyntax'>\n",
      "<class 'decimal.DivisionImpossible'>\n",
      "<class 'decimal.DivisionUndefined'>\n",
      "<class 'decimal.InvalidContext'>\n",
      "<class 'SystemError'>\n",
      "<class 'encodings.CodecRegistryError'>\n",
      "<class 'ReferenceError'>\n",
      "<class 'MemoryError'>\n",
      "<class 'BufferError'>\n",
      "<class 'Warning'>\n",
      "<class 'UserWarning'>\n",
      "<class 'getpass.GetPassWarning'>\n",
      "<class 'IPython.core.formatters.FormatterWarning'>\n",
      "<class 'EncodingWarning'>\n",
      "<class 'DeprecationWarning'>\n",
      "<class 'IPython.core.interactiveshell.ProvisionalWarning'>\n",
      "<class 'PendingDeprecationWarning'>\n",
      "<class 'SyntaxWarning'>\n",
      "<class 'RuntimeWarning'>\n",
      "<class 'zmq.asyncio.ProactorSelectorThreadWarning'>\n",
      "<class 'dateutil.parser._parser.UnknownTimezoneWarning'>\n",
      "<class 'FutureWarning'>\n",
      "<class 'IPython.core.completer.ProvisionalCompleterWarning'>\n",
      "<class 'ImportWarning'>\n",
      "<class 'UnicodeWarning'>\n",
      "<class 'BytesWarning'>\n",
      "<class 'ResourceWarning'>\n",
      "<class 'dateutil.tz.DeprecatedTzFormatWarning'>\n",
      "<class 'warnings._OptionError'>\n",
      "<class 'runpy._Error'>\n",
      "<class 're.error'>\n",
      "<class 'sre_parse.Verbose'>\n",
      "<class 'locale.Error'>\n",
      "<class 'subprocess.SubprocessError'>\n",
      "<class 'subprocess.CalledProcessError'>\n",
      "<class 'subprocess.TimeoutExpired'>\n",
      "<class 'zmq.error.ZMQBaseError'>\n",
      "<class 'zmq.error.ZMQError'>\n",
      "<class 'zmq.error.ContextTerminated'>\n",
      "<class 'zmq.error.Again'>\n",
      "<class 'zmq.error.InterruptedSystemCall'>\n",
      "<class 'zmq.error.ZMQBindError'>\n",
      "<class 'zmq.error.NotDone'>\n",
      "<class 'struct.error'>\n",
      "<class '_pickle.PickleError'>\n",
      "<class '_pickle.PicklingError'>\n",
      "<class '_pickle.UnpicklingError'>\n",
      "<class 'pickle._Stop'>\n",
      "<class 'tokenize.TokenError'>\n",
      "<class 'tokenize.StopTokenizing'>\n",
      "<class 'concurrent.futures._base.Error'>\n",
      "<class 'concurrent.futures._base.CancelledError'>\n",
      "<class 'concurrent.futures._base.TimeoutError'>\n",
      "<class 'concurrent.futures._base.InvalidStateError'>\n",
      "<class 'socket._GiveupOnSendfile'>\n",
      "<class 'binascii.Incomplete'>\n",
      "<class 'inspect.ClassFoundException'>\n",
      "<class 'inspect.EndOfBlock'>\n",
      "<class 'asyncio.exceptions.TimeoutError'>\n",
      "<class 'asyncio.exceptions.InvalidStateError'>\n",
      "<class 'asyncio.exceptions.LimitOverrunError'>\n",
      "<class 'asyncio.queues.QueueEmpty'>\n",
      "<class 'asyncio.queues.QueueFull'>\n",
      "<class 'zlib.error'>\n",
      "<class '_lzma.LZMAError'>\n",
      "<class 'shutil.RegistryError'>\n",
      "<class 'shutil._GiveupOnFastCopy'>\n",
      "<class 'traitlets.traitlets.TraitError'>\n",
      "<class 'copy.Error'>\n",
      "<class '_queue.Empty'>\n",
      "<class 'queue.Full'>\n",
      "<class 'ctypes.ArgumentError'>\n",
      "<class '_ctypes.COMError'>\n",
      "<class 'tornado.concurrent.ReturnValueIgnoredError'>\n",
      "<class 'argparse.ArgumentError'>\n",
      "<class 'argparse.ArgumentTypeError'>\n",
      "<class 'traitlets.config.loader.ConfigError'>\n",
      "<class 'traitlets.config.loader.ConfigLoaderError'>\n",
      "<class 'traitlets.config.loader.ArgumentError'>\n",
      "<class 'traitlets.config.loader.ConfigFileNotFound'>\n",
      "<class 'traitlets.config.configurable.ConfigurableError'>\n",
      "<class 'traitlets.config.configurable.MultipleInstanceError'>\n",
      "<class 'traitlets.config.application.ApplicationError'>\n",
      "<class 'jupyter_client.channels.InvalidPortNumber'>\n",
      "<class 'jupyter_client.localinterfaces.NoIPAddresses'>\n",
      "<class '_csv.Error'>\n",
      "<class 'zipfile.BadZipFile'>\n",
      "<class 'zipfile.LargeZipFile'>\n",
      "<class 'uu.Error'>\n",
      "<class 'email.errors.MessageError'>\n",
      "<class 'email.errors.MessageParseError'>\n",
      "<class 'email.errors.HeaderParseError'>\n",
      "<class 'email.errors.BoundaryError'>\n",
      "<class 'email.errors.MultipartConversionError'>\n",
      "<class 'email.errors.CharsetError'>\n",
      "<class 'jupyter_client.multikernelmanager.DuplicateKernelError'>\n",
      "<class 'pydoc.ErrorDuringImport'>\n",
      "<class 'executing.executing.NotOneValueFound'>\n",
      "<class 'pure_eval.utils.CannotEval'>\n",
      "<class 'pygments.util.OptionError'>\n",
      "<class 'bdb.BdbQuit'>\n",
      "<class 'pdb.Restart'>\n",
      "<class 'IPython.utils.process.FindCmdError'>\n",
      "<class 'IPython.utils.path.HomeDirError'>\n",
      "<class 'IPython.core.profiledir.ProfileDirError'>\n",
      "<class 'IPython.core.error.IPythonCoreError'>\n",
      "<class 'IPython.core.error.TryNext'>\n",
      "<class 'IPython.core.error.UsageError'>\n",
      "<class 'IPython.core.error.StdinNotImplementedError'>\n",
      "<class 'IPython.core.error.InputRejected'>\n",
      "<class 'getopt.GetoptError'>\n",
      "<class 'pygments.filters.ErrorToken'>\n",
      "<class 'IPython.core.prefilter.PrefilterError'>\n",
      "<class 'IPython.core.alias.AliasError'>\n",
      "<class 'IPython.core.alias.InvalidAliasError'>\n",
      "<class 'sqlite3.Error'>\n",
      "<class 'sqlite3.InterfaceError'>\n",
      "<class 'sqlite3.DatabaseError'>\n",
      "<class 'sqlite3.InternalError'>\n",
      "<class 'sqlite3.OperationalError'>\n",
      "<class 'sqlite3.ProgrammingError'>\n",
      "<class 'sqlite3.IntegrityError'>\n",
      "<class 'sqlite3.DataError'>\n",
      "<class 'sqlite3.NotSupportedError'>\n",
      "<class 'sqlite3.Warning'>\n",
      "<class 'exceptiongroup.ExceptionGroup'>\n",
      "<class 'IPython.core.interactiveshell.SpaceInInput'>\n",
      "<class 'xml.dom.DOMException'>\n",
      "<class 'xml.dom.IndexSizeErr'>\n",
      "<class 'xml.dom.DomstringSizeErr'>\n",
      "<class 'xml.dom.HierarchyRequestErr'>\n",
      "<class 'xml.dom.WrongDocumentErr'>\n",
      "<class 'xml.dom.InvalidCharacterErr'>\n",
      "<class 'xml.dom.NoDataAllowedErr'>\n",
      "<class 'xml.dom.NoModificationAllowedErr'>\n",
      "<class 'xml.dom.NotFoundErr'>\n",
      "<class 'xml.dom.NotSupportedErr'>\n",
      "<class 'xml.dom.InuseAttributeErr'>\n",
      "<class 'xml.dom.InvalidStateErr'>\n",
      "<class 'xml.dom.SyntaxErr'>\n",
      "<class 'xml.dom.InvalidModificationErr'>\n",
      "<class 'xml.dom.NamespaceErr'>\n",
      "<class 'xml.dom.InvalidAccessErr'>\n",
      "<class 'xml.dom.ValidationErr'>\n",
      "<class 'prompt_toolkit.validation.ValidationError'>\n",
      "<class 'prompt_toolkit.buffer.EditReadOnlyBuffer'>\n",
      "<class 'prompt_toolkit.buffer._Retry'>\n",
      "<class 'prompt_toolkit.layout.layout.InvalidLayoutError'>\n",
      "<class 'prompt_toolkit.renderer.HeightIsUnknownError'>\n",
      "<class 'xml.parsers.expat.ExpatError'>\n",
      "<class 'xml.dom.expatbuilder.ParseEscape'>\n",
      "<class 'IPython.core.guarded_eval.GuardRejection'>\n",
      "<class 'parso.parser.ParserSyntaxError'>\n",
      "<class 'parso.parser.InternalParseError'>\n",
      "<class 'parso.python.diff._PositionUpdatingFinished'>\n",
      "<class 'jedi.inference.helpers.SimpleGetItemNotFound'>\n",
      "<class 'jedi.inference.utils.UncaughtAttributeError'>\n",
      "<class 'jedi.inference.base_value.HasNoContext'>\n",
      "<class 'jedi.inference.arguments.ParamIssue'>\n",
      "<class 'jedi.api.exceptions._JediError'>\n",
      "<class 'jedi.api.exceptions.InternalError'>\n",
      "<class 'jedi.api.exceptions.WrongVersion'>\n",
      "<class 'jedi.api.exceptions.RefactoringError'>\n",
      "<class 'jedi.api.helpers.OnErrorLeaf'>\n",
      "<class 'jedi.api.environment.InvalidPythonEnvironment'>\n",
      "<class 'http.client.HTTPException'>\n",
      "<class 'http.client.NotConnected'>\n",
      "<class 'http.client.InvalidURL'>\n",
      "<class 'http.client.UnknownProtocol'>\n",
      "<class 'http.client.UnknownTransferEncoding'>\n",
      "<class 'http.client.UnimplementedFileMode'>\n",
      "<class 'http.client.IncompleteRead'>\n",
      "<class 'http.client.ImproperConnectionState'>\n",
      "<class 'http.client.CannotSendRequest'>\n",
      "<class 'http.client.CannotSendHeader'>\n",
      "<class 'http.client.ResponseNotReady'>\n",
      "<class 'http.client.BadStatusLine'>\n",
      "<class 'http.client.RemoteDisconnected'>\n",
      "<class 'http.client.LineTooLong'>\n",
      "<class 'IPython.core.magics.code.InteractivelyDefined'>\n",
      "<class 'IPython.terminal.embed.KillEmbedded'>\n",
      "<class 'psutil.Error'>\n",
      "<class 'psutil.NoSuchProcess'>\n",
      "<class 'psutil.ZombieProcess'>\n",
      "<class 'psutil.AccessDenied'>\n",
      "<class 'psutil.TimeoutExpired'>\n",
      "<class '_psutil_windows.Error'>\n",
      "<class '_psutil_windows.TimeoutExpired'>\n",
      "<class '_psutil_windows.TimeoutAbandoned'>\n",
      "<class 'tornado.gen.KeyReuseError'>\n",
      "<class 'tornado.gen.UnknownKeyError'>\n",
      "<class 'tornado.gen.LeakedCallbackError'>\n",
      "<class 'tornado.gen.BadYieldError'>\n",
      "<class 'tornado.gen.ReturnValueIgnoredError'>\n",
      "<class 'tornado.gen.Return'>\n",
      "<class 'tornado.queues.QueueEmpty'>\n",
      "<class 'tornado.queues.QueueFull'>\n",
      "<class '_pydev_bundle._pydev_saved_modules.DebuggerInitializationError'>\n",
      "<class 'xmlrpc.client.Error'>\n",
      "<class 'xmlrpc.client.ProtocolError'>\n",
      "<class 'xmlrpc.client.ResponseError'>\n",
      "<class 'xmlrpc.client.Fault'>\n",
      "<class '_pydevd_bundle.pydevd_runpy._Error'>\n",
      "<class '_pydevd_bundle.pydevd_resolver.UnableToResolveVariableException'>\n",
      "<class '_pydev_bundle.pydev_monkey.InvalidTypeInArgsException'>\n",
      "None\n"
     ]
    }
   ],
   "source": [
    "import inspect \n",
    "\n",
    "def print_exception_hierarchy(base_exception):\n",
    "    print(base_exception)\n",
    "    for subclass in base_exception.__subclasses__():\n",
    "        print_exception_hierarchy(subclass)\n",
    "\n",
    "print(\"exception hierarchy\")\n",
    "print( print_exception_hierarchy(Exception) )\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "\n",
    "Arithmatic error class occurs during arimatical operations between the variables "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "division by zero\n"
     ]
    }
   ],
   "source": [
    "# Example 1 : zero division error :\n",
    "import math \n",
    "\n",
    "try:\n",
    "     6/0\n",
    "except ZeroDivisionError as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "math range error\n"
     ]
    }
   ],
   "source": [
    "# Example 2 : Overflow Error\n",
    "\n",
    "try:\n",
    "    math.exp(1000)\n",
    "except OverflowError as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "\n",
    "lookupError class will be used when the look up operation in the code like getting value for key in a dictionary or extracting particular value from list based on index.\n",
    "it is the parent class for both KeyError & IndexError. examples below :\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "total number of elements in the list is 4 only \n",
      "key not found in the dictionary\n"
     ]
    }
   ],
   "source": [
    "# IndexError \n",
    "\n",
    "try:\n",
    "    l= ['a','b','c','d']\n",
    "    print(l[5])\n",
    "except IndexError as e:\n",
    "    print(f\"total number of elements in the list is {len(l)} only \")\n",
    "\n",
    "# keyError\n",
    "try:\n",
    "    dict = {'a':1,'b':2,'c':3}\n",
    "    print(dict['d'])\n",
    "except KeyError as e:\n",
    "    print(f\"key not found in the dictionary\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "\n",
    "importError is general exception class raised when there is error during import operations . it handles all the errors related to import process and it is parent class for ModuleNotFoundError which occurs when the module is not available in python to import.\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "module not found\n"
     ]
    }
   ],
   "source": [
    "# Example :\n",
    "\n",
    "try :\n",
    "    import special_module\n",
    "except ModuleNotFoundError as e:\n",
    "    print(\"module not found\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Q6. List down some best practices for exception handling in python.\n",
    "\n",
    "1) it is better to use only specic exception class based on the relavance instead of adding all\n",
    "2) using general exceptions is not advisable unless the error class is difficult to catch \n",
    "3) In error handling , print always meaningful message to the user\n",
    "4) always try to log in file to understand the error\n",
    "5) log it inside the file instead of console\n",
    "6) do valid messgaes and proper documentation to debug in the future \n",
    "6) always avoid to write multiple exception handling \n",
    "\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
